"""true elter token

Revision ID: d62a7fe2c68f
Revises: e39a5be78bb7
Create Date: 2024-03-06 12:58:15.474172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62a7fe2c68f'
down_revision: Union[str, None] = 'e39a5be78bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('exp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'exp')
    # ### end Alembic commands ###
