"""DB creation

Revision ID: b91ad0be4823
Revises: 
Create Date: 2024-03-05 15:01:09.203824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91ad0be4823'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'salt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
